name: Build

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: pwsh
        run: |
          $branch = $env:GITHUB_REF -replace 'refs/heads/', ''
          echo "BRANCH_NAME=$branch" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          if ( $branch -eq 'develop' ) {
              echo "BUILD=Debug" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
              echo "BUILD=Release" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build --nologo /p:Configuration=${{ env.BUILD }} /p:Version=1.1.0

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: src/bin/${{ env.BUILD }}/
